apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-carto
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  CARTO_API_KEY: {{ .Values.app.cartoApiKey | default "" | quote }}
